version: "3.8"
services:
  postgres:
    container_name: blog-app-db
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=.env.db_username
      - POSTGRES_PASSWORD=.env.db_password
      - POSTGRES_DB=blog-app
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local
