version: "3.8"
services:
  postgres:
    container_name: blog-app-db
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=.env.db_username
      - POSTGRES_PASSWORD=.env.db_password
      - POSTGRES_DB=blog-app
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    container_name: blog-app-session
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning --requirepass 23092004
    volumes:
      - session_data:/session_data

volumes:
  db_data:
    driver: local
  session_data:
    driver: local
